// This file is generated by utils/regex-gen.ts

export const defaultScanPatterns = {
  def: /\[\[(?!@)((?:.)+?)\]\]/g,
  ref: /\[\[@((?:.)+?)\]\]/g,
};

export type ScanPatterns = typeof defaultScanPatterns;